@ECHO OFF

:: 37 excel questions:
python geo_qa.py question "Who is the president of China?"
python geo_qa.py question "Who is the president of Portugal?"
python geo_qa.py question "Who is the president of Guam?"
python geo_qa.py question "Who is the prime minister of Eswatini?"
python geo_qa.py question "Who is the prime minister of Tonga?"
python geo_qa.py question "What is the population of Isle of Man?"
python geo_qa.py question "What is the population of Tokelau?"
python geo_qa.py question "What is the population of Djibouti?"
python geo_qa.py question "What is the area of Mauritius?"
python geo_qa.py question "What is the area of Luxembourg?"
python geo_qa.py question "What is the area of Guadeloupe?"
python geo_qa.py question "What is the form of government in Argentina?"
python geo_qa.py question "What is the form of government in Sweden?"
python geo_qa.py question "What is the form of government in Bahrain?"
python geo_qa.py question "What is the form of government in North Macedonia?"
python geo_qa.py question "What is the capital of Burundi?"
python geo_qa.py question "What is the capital of Mongolia?"
python geo_qa.py question "What is the capital of Andorra?"
python geo_qa.py question "What is the capital of Saint Helena, Ascension and Tristan da Cunha?"
python geo_qa.py question "What is the capital of Greenland?"
python geo_qa.py question "List all countries whose capital name contains the string hi"
python geo_qa.py question "List all countries whose capital name contains the string free"
python geo_qa.py question "List all countries whose capital name contains the string alo"
python geo_qa.py question "List all countries whose capital name contains the string baba"
python geo_qa.py question "How many Absolute monarchy are also Unitary state?"
python geo_qa.py question "How many Dictatorship are also Presidential system?"
python geo_qa.py question "How many Dictatorship are also Authoritarian?"
python geo_qa.py question "How many presidents were born in Iceland?"
python geo_qa.py question "How many presidents were born in Republic of Ireland?"
python geo_qa.py question "When was the president of Fiji born?"
python geo_qa.py question "When was the president of United States born?"
python geo_qa.py question "Where was the president of Indonesia born?"
python geo_qa.py question "Where was the president of Uruguay born?"
python geo_qa.py question "Where was the prime minister of Solomon Islands born?"
python geo_qa.py question "When was the prime minister of Lesotho born?"
python geo_qa.py question "Who is Denis Sassou Nguesso?"
python geo_qa.py question "Who is David Kabua?"


::set country=Indonesia
:: python geo_qa.py question "What is the area of %country%?"
:: python geo_qa.py question "What is the population of %country%?"
:: python geo_qa.py question "What is the capital of %country%?"
:: python geo_qa.py question "Who is the president of %country%?"
:: python geo_qa.py question "Who is the prime minister of %country%?"
:: python geo_qa.py question "What is the form of government in %country%?"
:: python geo_qa.py question "When was the president of %country% born?"
:: python geo_qa.py question "Where was the president of %country% born?"
:: python geo_qa.py question "When was the prime minister of %country% born?"
:: python geo_qa.py question "Where was the prime minister of %country% born?"
:: python geo_qa.py question "Where was the prime minister of %country% born?"
:: python geo_qa.py question "How many Unitary state are also Presidential system?"
:: python geo_qa.py question "List all countries whose capital name contains the string Bei"
:: python geo_qa.py question "How many presidents were born in Indonesia?"
:: python geo_qa.py question "Who is Joe Biden?"
:: python geo_qa.py question "Who is Narendra Modi?"